/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "platform/device/driver/ethernet_manager/proto/phy/general_cfg.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(platform_ethernet_phy_general_EthPhyGeneral, platform_ethernet_phy_general_EthPhyGeneral, AUTO)




