/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_PLATFORM_ETHERNET_COMMON_PLATFORM_DEVICE_DRIVER_ETHERNET_MANAGER_PROTO_COMMON_PB_H_INCLUDED
#define PB_PLATFORM_ETHERNET_COMMON_PLATFORM_DEVICE_DRIVER_ETHERNET_MANAGER_PROTO_COMMON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _platform_ethernet_common_EthSpeedType {
    platform_ethernet_common_EthSpeedType_ETH_SPEED_UNKNOWN = 0,
    platform_ethernet_common_EthSpeedType_ETH_SPEED_100M = 1,
    platform_ethernet_common_EthSpeedType_ETH_SPEED_1000M = 2
} platform_ethernet_common_EthSpeedType;

/* Helper constants for enums */
#define _platform_ethernet_common_EthSpeedType_MIN platform_ethernet_common_EthSpeedType_ETH_SPEED_UNKNOWN
#define _platform_ethernet_common_EthSpeedType_MAX platform_ethernet_common_EthSpeedType_ETH_SPEED_1000M
#define _platform_ethernet_common_EthSpeedType_ARRAYSIZE ((platform_ethernet_common_EthSpeedType)(platform_ethernet_common_EthSpeedType_ETH_SPEED_1000M+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
