/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "platform/device/driver/ethernet_manager/proto/hw_info.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(platform_ethernet_hw_info_SwitchPort, platform_ethernet_hw_info_SwitchPort, AUTO)


PB_BIND(platform_ethernet_hw_info_HwDeviceInfo, platform_ethernet_hw_info_HwDeviceInfo, AUTO)


PB_BIND(platform_ethernet_hw_info_HwMcuInfo, platform_ethernet_hw_info_HwMcuInfo, AUTO)


PB_BIND(platform_ethernet_hw_info_HwPhyInfo, platform_ethernet_hw_info_HwPhyInfo, AUTO)


PB_BIND(platform_ethernet_hw_info_HwSwitchInfo, platform_ethernet_hw_info_HwSwitchInfo, AUTO)


PB_BIND(platform_ethernet_hw_info_HardwareInfo, platform_ethernet_hw_info_HardwareInfo, AUTO)







