/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_PLATFORM_ETHERNET_HW_INFO_PLATFORM_DEVICE_DRIVER_ETHERNET_MANAGER_PROTO_HW_INFO_PB_H_INCLUDED
#define PB_PLATFORM_ETHERNET_HW_INFO_PLATFORM_DEVICE_DRIVER_ETHERNET_MANAGER_PROTO_HW_INFO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _platform_ethernet_hw_info_HwDeviceType {
    platform_ethernet_hw_info_HwDeviceType_NET_DEVICE_UNKNOWN = 0,
    platform_ethernet_hw_info_HwDeviceType_NET_DEVICE_MCU = 1,
    platform_ethernet_hw_info_HwDeviceType_NET_DEVICE_SOC = 2,
    platform_ethernet_hw_info_HwDeviceType_NET_DEVICE_EXTERNAL = 3,
    platform_ethernet_hw_info_HwDeviceType_NET_DEVICE_CASCADE = 4
} platform_ethernet_hw_info_HwDeviceType;

typedef enum _platform_ethernet_hw_info_HwMcuType {
    platform_ethernet_hw_info_HwMcuType_NET_MCU_UNKNOWN = 0,
    platform_ethernet_hw_info_HwMcuType_NET_MCU_TC39X = 1
} platform_ethernet_hw_info_HwMcuType;

typedef enum _platform_ethernet_hw_info_HwPhyType {
    platform_ethernet_hw_info_HwPhyType_NET_PHY_UNKNOWN = 0,
    platform_ethernet_hw_info_HwPhyType_NET_PHY_88Q2112 = 1
} platform_ethernet_hw_info_HwPhyType;

typedef enum _platform_ethernet_hw_info_HwSwitchType {
    platform_ethernet_hw_info_HwSwitchType_NET_SWITCH_UNKNOWN = 0,
    platform_ethernet_hw_info_HwSwitchType_NET_SWITCH_88Q5072 = 1,
    platform_ethernet_hw_info_HwSwitchType_NET_SWITCH_88Q6113 = 2
} platform_ethernet_hw_info_HwSwitchType;

/* Struct definitions */
typedef struct _platform_ethernet_hw_info_HardwareInfo {
    pb_callback_t device_info;
    pb_callback_t mcu_info;
    pb_callback_t phy_info;
    pb_callback_t switch_info;
} platform_ethernet_hw_info_HardwareInfo;

typedef struct _platform_ethernet_hw_info_HwMcuInfo {
    bool has_index;
    uint32_t index;
    bool has_type;
    platform_ethernet_hw_info_HwMcuType type;
} platform_ethernet_hw_info_HwMcuInfo;

typedef struct _platform_ethernet_hw_info_HwPhyInfo {
    bool has_index;
    uint32_t index;
    bool has_type;
    platform_ethernet_hw_info_HwPhyType type;
} platform_ethernet_hw_info_HwPhyInfo;

typedef struct _platform_ethernet_hw_info_HwSwitchInfo {
    bool has_index;
    uint32_t index;
    bool has_type;
    platform_ethernet_hw_info_HwSwitchType type;
} platform_ethernet_hw_info_HwSwitchInfo;

typedef struct _platform_ethernet_hw_info_SwitchPort {
    bool has_switch_index;
    uint32_t switch_index;
    bool has_switch_port_index;
    uint32_t switch_port_index;
} platform_ethernet_hw_info_SwitchPort;

typedef struct _platform_ethernet_hw_info_HwDeviceInfo {
    pb_callback_t name;
    bool has_type;
    platform_ethernet_hw_info_HwDeviceType type;
    bool has_mcu_index;
    uint32_t mcu_index;
    bool has_phy_index;
    uint32_t phy_index;
    bool has_port_index;
    platform_ethernet_hw_info_SwitchPort port_index;
    bool has_cascade_port;
    platform_ethernet_hw_info_SwitchPort cascade_port;
} platform_ethernet_hw_info_HwDeviceInfo;


/* Helper constants for enums */
#define _platform_ethernet_hw_info_HwDeviceType_MIN platform_ethernet_hw_info_HwDeviceType_NET_DEVICE_UNKNOWN
#define _platform_ethernet_hw_info_HwDeviceType_MAX platform_ethernet_hw_info_HwDeviceType_NET_DEVICE_CASCADE
#define _platform_ethernet_hw_info_HwDeviceType_ARRAYSIZE ((platform_ethernet_hw_info_HwDeviceType)(platform_ethernet_hw_info_HwDeviceType_NET_DEVICE_CASCADE+1))

#define _platform_ethernet_hw_info_HwMcuType_MIN platform_ethernet_hw_info_HwMcuType_NET_MCU_UNKNOWN
#define _platform_ethernet_hw_info_HwMcuType_MAX platform_ethernet_hw_info_HwMcuType_NET_MCU_TC39X
#define _platform_ethernet_hw_info_HwMcuType_ARRAYSIZE ((platform_ethernet_hw_info_HwMcuType)(platform_ethernet_hw_info_HwMcuType_NET_MCU_TC39X+1))

#define _platform_ethernet_hw_info_HwPhyType_MIN platform_ethernet_hw_info_HwPhyType_NET_PHY_UNKNOWN
#define _platform_ethernet_hw_info_HwPhyType_MAX platform_ethernet_hw_info_HwPhyType_NET_PHY_88Q2112
#define _platform_ethernet_hw_info_HwPhyType_ARRAYSIZE ((platform_ethernet_hw_info_HwPhyType)(platform_ethernet_hw_info_HwPhyType_NET_PHY_88Q2112+1))

#define _platform_ethernet_hw_info_HwSwitchType_MIN platform_ethernet_hw_info_HwSwitchType_NET_SWITCH_UNKNOWN
#define _platform_ethernet_hw_info_HwSwitchType_MAX platform_ethernet_hw_info_HwSwitchType_NET_SWITCH_88Q6113
#define _platform_ethernet_hw_info_HwSwitchType_ARRAYSIZE ((platform_ethernet_hw_info_HwSwitchType)(platform_ethernet_hw_info_HwSwitchType_NET_SWITCH_88Q6113+1))


/* Initializer values for message structs */
#define platform_ethernet_hw_info_SwitchPort_init_default {false, 0, false, 0}
#define platform_ethernet_hw_info_HwDeviceInfo_init_default {{{NULL}, NULL}, false, _platform_ethernet_hw_info_HwDeviceType_MIN, false, 0, false, 0, false, platform_ethernet_hw_info_SwitchPort_init_default, false, platform_ethernet_hw_info_SwitchPort_init_default}
#define platform_ethernet_hw_info_HwMcuInfo_init_default {false, 0, false, _platform_ethernet_hw_info_HwMcuType_MIN}
#define platform_ethernet_hw_info_HwPhyInfo_init_default {false, 0, false, _platform_ethernet_hw_info_HwPhyType_MIN}
#define platform_ethernet_hw_info_HwSwitchInfo_init_default {false, 0, false, _platform_ethernet_hw_info_HwSwitchType_MIN}
#define platform_ethernet_hw_info_HardwareInfo_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define platform_ethernet_hw_info_SwitchPort_init_zero {false, 0, false, 0}
#define platform_ethernet_hw_info_HwDeviceInfo_init_zero {{{NULL}, NULL}, false, _platform_ethernet_hw_info_HwDeviceType_MIN, false, 0, false, 0, false, platform_ethernet_hw_info_SwitchPort_init_zero, false, platform_ethernet_hw_info_SwitchPort_init_zero}
#define platform_ethernet_hw_info_HwMcuInfo_init_zero {false, 0, false, _platform_ethernet_hw_info_HwMcuType_MIN}
#define platform_ethernet_hw_info_HwPhyInfo_init_zero {false, 0, false, _platform_ethernet_hw_info_HwPhyType_MIN}
#define platform_ethernet_hw_info_HwSwitchInfo_init_zero {false, 0, false, _platform_ethernet_hw_info_HwSwitchType_MIN}
#define platform_ethernet_hw_info_HardwareInfo_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define platform_ethernet_hw_info_HardwareInfo_device_info_tag 1
#define platform_ethernet_hw_info_HardwareInfo_mcu_info_tag 2
#define platform_ethernet_hw_info_HardwareInfo_phy_info_tag 3
#define platform_ethernet_hw_info_HardwareInfo_switch_info_tag 4
#define platform_ethernet_hw_info_HwMcuInfo_index_tag 1
#define platform_ethernet_hw_info_HwMcuInfo_type_tag 2
#define platform_ethernet_hw_info_HwPhyInfo_index_tag 1
#define platform_ethernet_hw_info_HwPhyInfo_type_tag 2
#define platform_ethernet_hw_info_HwSwitchInfo_index_tag 1
#define platform_ethernet_hw_info_HwSwitchInfo_type_tag 2
#define platform_ethernet_hw_info_SwitchPort_switch_index_tag 1
#define platform_ethernet_hw_info_SwitchPort_switch_port_index_tag 2
#define platform_ethernet_hw_info_HwDeviceInfo_name_tag 1
#define platform_ethernet_hw_info_HwDeviceInfo_type_tag 2
#define platform_ethernet_hw_info_HwDeviceInfo_mcu_index_tag 3
#define platform_ethernet_hw_info_HwDeviceInfo_phy_index_tag 4
#define platform_ethernet_hw_info_HwDeviceInfo_port_index_tag 5
#define platform_ethernet_hw_info_HwDeviceInfo_cascade_port_tag 6

/* Struct field encoding specification for nanopb */
#define platform_ethernet_hw_info_SwitchPort_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   switch_index,      1) \
X(a, STATIC,   OPTIONAL, UINT32,   switch_port_index,   2)
#define platform_ethernet_hw_info_SwitchPort_CALLBACK NULL
#define platform_ethernet_hw_info_SwitchPort_DEFAULT NULL

#define platform_ethernet_hw_info_HwDeviceInfo_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, UENUM,    type,              2) \
X(a, STATIC,   OPTIONAL, UINT32,   mcu_index,         3) \
X(a, STATIC,   OPTIONAL, UINT32,   phy_index,         4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  port_index,        5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cascade_port,      6)
#define platform_ethernet_hw_info_HwDeviceInfo_CALLBACK pb_default_field_callback
#define platform_ethernet_hw_info_HwDeviceInfo_DEFAULT NULL
#define platform_ethernet_hw_info_HwDeviceInfo_port_index_MSGTYPE platform_ethernet_hw_info_SwitchPort
#define platform_ethernet_hw_info_HwDeviceInfo_cascade_port_MSGTYPE platform_ethernet_hw_info_SwitchPort

#define platform_ethernet_hw_info_HwMcuInfo_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   index,             1) \
X(a, STATIC,   OPTIONAL, UENUM,    type,              2)
#define platform_ethernet_hw_info_HwMcuInfo_CALLBACK NULL
#define platform_ethernet_hw_info_HwMcuInfo_DEFAULT NULL

#define platform_ethernet_hw_info_HwPhyInfo_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   index,             1) \
X(a, STATIC,   OPTIONAL, UENUM,    type,              2)
#define platform_ethernet_hw_info_HwPhyInfo_CALLBACK NULL
#define platform_ethernet_hw_info_HwPhyInfo_DEFAULT NULL

#define platform_ethernet_hw_info_HwSwitchInfo_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   index,             1) \
X(a, STATIC,   OPTIONAL, UENUM,    type,              2)
#define platform_ethernet_hw_info_HwSwitchInfo_CALLBACK NULL
#define platform_ethernet_hw_info_HwSwitchInfo_DEFAULT NULL

#define platform_ethernet_hw_info_HardwareInfo_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  device_info,       1) \
X(a, CALLBACK, REPEATED, MESSAGE,  mcu_info,          2) \
X(a, CALLBACK, REPEATED, MESSAGE,  phy_info,          3) \
X(a, CALLBACK, REPEATED, MESSAGE,  switch_info,       4)
#define platform_ethernet_hw_info_HardwareInfo_CALLBACK pb_default_field_callback
#define platform_ethernet_hw_info_HardwareInfo_DEFAULT NULL
#define platform_ethernet_hw_info_HardwareInfo_device_info_MSGTYPE platform_ethernet_hw_info_HwDeviceInfo
#define platform_ethernet_hw_info_HardwareInfo_mcu_info_MSGTYPE platform_ethernet_hw_info_HwMcuInfo
#define platform_ethernet_hw_info_HardwareInfo_phy_info_MSGTYPE platform_ethernet_hw_info_HwPhyInfo
#define platform_ethernet_hw_info_HardwareInfo_switch_info_MSGTYPE platform_ethernet_hw_info_HwSwitchInfo

extern const pb_msgdesc_t platform_ethernet_hw_info_SwitchPort_msg;
extern const pb_msgdesc_t platform_ethernet_hw_info_HwDeviceInfo_msg;
extern const pb_msgdesc_t platform_ethernet_hw_info_HwMcuInfo_msg;
extern const pb_msgdesc_t platform_ethernet_hw_info_HwPhyInfo_msg;
extern const pb_msgdesc_t platform_ethernet_hw_info_HwSwitchInfo_msg;
extern const pb_msgdesc_t platform_ethernet_hw_info_HardwareInfo_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define platform_ethernet_hw_info_SwitchPort_fields &platform_ethernet_hw_info_SwitchPort_msg
#define platform_ethernet_hw_info_HwDeviceInfo_fields &platform_ethernet_hw_info_HwDeviceInfo_msg
#define platform_ethernet_hw_info_HwMcuInfo_fields &platform_ethernet_hw_info_HwMcuInfo_msg
#define platform_ethernet_hw_info_HwPhyInfo_fields &platform_ethernet_hw_info_HwPhyInfo_msg
#define platform_ethernet_hw_info_HwSwitchInfo_fields &platform_ethernet_hw_info_HwSwitchInfo_msg
#define platform_ethernet_hw_info_HardwareInfo_fields &platform_ethernet_hw_info_HardwareInfo_msg

/* Maximum encoded size of messages (where known) */
#define platform_ethernet_hw_info_SwitchPort_size 12
/* platform_ethernet_hw_info_HwDeviceInfo_size depends on runtime parameters */
#define platform_ethernet_hw_info_HwMcuInfo_size 8
#define platform_ethernet_hw_info_HwPhyInfo_size 8
#define platform_ethernet_hw_info_HwSwitchInfo_size 8
/* platform_ethernet_hw_info_HardwareInfo_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
