/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "platform/device/driver/ethernet_manager/proto/mcu/general_cfg.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(platform_ethernet_mcu_general_EthMcuFlag, platform_ethernet_mcu_general_EthMcuFlag, AUTO)


PB_BIND(platform_ethernet_mcu_general_EthMcuGeneral, platform_ethernet_mcu_general_EthMcuGeneral, AUTO)



