/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_PLATFORM_ETHERNET_MCU_GENERAL_PLATFORM_DEVICE_DRIVER_ETHERNET_MANAGER_PROTO_MCU_GENERAL_CFG_PB_H_INCLUDED
#define PB_PLATFORM_ETHERNET_MCU_GENERAL_PLATFORM_DEVICE_DRIVER_ETHERNET_MANAGER_PROTO_MCU_GENERAL_CFG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _platform_ethernet_mcu_general_EthMcuFlag {
    bool has_support_config_change;
    bool support_config_change;
    bool has_switch_support_vlan;
    bool switch_support_vlan;
} platform_ethernet_mcu_general_EthMcuFlag;

typedef struct _platform_ethernet_mcu_general_EthMcuGeneral {
    pb_callback_t version;
    bool has_mcu_flag;
    platform_ethernet_mcu_general_EthMcuFlag mcu_flag;
    pb_callback_t mac;
    pb_callback_t ip;
    pb_callback_t gateway;
    pb_callback_t netmask;
} platform_ethernet_mcu_general_EthMcuGeneral;


/* Initializer values for message structs */
#define platform_ethernet_mcu_general_EthMcuFlag_init_default {false, 0, false, 0}
#define platform_ethernet_mcu_general_EthMcuGeneral_init_default {{{NULL}, NULL}, false, platform_ethernet_mcu_general_EthMcuFlag_init_default, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define platform_ethernet_mcu_general_EthMcuFlag_init_zero {false, 0, false, 0}
#define platform_ethernet_mcu_general_EthMcuGeneral_init_zero {{{NULL}, NULL}, false, platform_ethernet_mcu_general_EthMcuFlag_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define platform_ethernet_mcu_general_EthMcuFlag_support_config_change_tag 1
#define platform_ethernet_mcu_general_EthMcuFlag_switch_support_vlan_tag 2
#define platform_ethernet_mcu_general_EthMcuGeneral_version_tag 1
#define platform_ethernet_mcu_general_EthMcuGeneral_mcu_flag_tag 2
#define platform_ethernet_mcu_general_EthMcuGeneral_mac_tag 3
#define platform_ethernet_mcu_general_EthMcuGeneral_ip_tag 4
#define platform_ethernet_mcu_general_EthMcuGeneral_gateway_tag 5
#define platform_ethernet_mcu_general_EthMcuGeneral_netmask_tag 6

/* Struct field encoding specification for nanopb */
#define platform_ethernet_mcu_general_EthMcuFlag_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     support_config_change,   1) \
X(a, STATIC,   OPTIONAL, BOOL,     switch_support_vlan,   2)
#define platform_ethernet_mcu_general_EthMcuFlag_CALLBACK NULL
#define platform_ethernet_mcu_general_EthMcuFlag_DEFAULT NULL

#define platform_ethernet_mcu_general_EthMcuGeneral_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   version,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mcu_flag,          2) \
X(a, CALLBACK, OPTIONAL, STRING,   mac,               3) \
X(a, CALLBACK, OPTIONAL, STRING,   ip,                4) \
X(a, CALLBACK, OPTIONAL, STRING,   gateway,           5) \
X(a, CALLBACK, OPTIONAL, STRING,   netmask,           6)
#define platform_ethernet_mcu_general_EthMcuGeneral_CALLBACK pb_default_field_callback
#define platform_ethernet_mcu_general_EthMcuGeneral_DEFAULT NULL
#define platform_ethernet_mcu_general_EthMcuGeneral_mcu_flag_MSGTYPE platform_ethernet_mcu_general_EthMcuFlag

extern const pb_msgdesc_t platform_ethernet_mcu_general_EthMcuFlag_msg;
extern const pb_msgdesc_t platform_ethernet_mcu_general_EthMcuGeneral_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define platform_ethernet_mcu_general_EthMcuFlag_fields &platform_ethernet_mcu_general_EthMcuFlag_msg
#define platform_ethernet_mcu_general_EthMcuGeneral_fields &platform_ethernet_mcu_general_EthMcuGeneral_msg

/* Maximum encoded size of messages (where known) */
#define platform_ethernet_mcu_general_EthMcuFlag_size 4
/* platform_ethernet_mcu_general_EthMcuGeneral_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
