/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_PLATFORM_ETHERNET_SWITCH_PORT_VLAN_PLATFORM_DEVICE_DRIVER_ETHERNET_MANAGER_PROTO_SWITCH_PORT_VLAN_CFG_PB_H_INCLUDED
#define PB_PLATFORM_ETHERNET_SWITCH_PORT_VLAN_PLATFORM_DEVICE_DRIVER_ETHERNET_MANAGER_PROTO_SWITCH_PORT_VLAN_CFG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _platform_ethernet_switch_port_vlan_EthSwitchVlanMemberMode {
    platform_ethernet_switch_port_vlan_EthSwitchVlanMemberMode_ETH_SWITCH_MEMBER_UNMODIFIED = 0,
    platform_ethernet_switch_port_vlan_EthSwitchVlanMemberMode_ETH_SWITCH_MEMBER_UNTAGGED = 1,
    platform_ethernet_switch_port_vlan_EthSwitchVlanMemberMode_ETH_SWITCH_MEMBER_TAGGED = 2,
    platform_ethernet_switch_port_vlan_EthSwitchVlanMemberMode_ETH_SWITCH_NOT_MEMBER = 3
} platform_ethernet_switch_port_vlan_EthSwitchVlanMemberMode;

/* Struct definitions */
typedef struct _platform_ethernet_switch_port_vlan_EthSwitchPortVlanTable {
    pb_callback_t port_vlan_node;
} platform_ethernet_switch_port_vlan_EthSwitchPortVlanTable;

typedef struct _platform_ethernet_switch_port_vlan_EthSwitchPortVlanMode {
    bool has_port_index;
    uint32_t port_index;
    bool has_port_mode;
    platform_ethernet_switch_port_vlan_EthSwitchVlanMemberMode port_mode;
} platform_ethernet_switch_port_vlan_EthSwitchPortVlanMode;

typedef struct _platform_ethernet_switch_port_vlan_EthSwitchPortVlanNode {
    bool has_vlan_id;
    uint32_t vlan_id;
    pb_callback_t port_vlan;
} platform_ethernet_switch_port_vlan_EthSwitchPortVlanNode;


/* Helper constants for enums */
#define _platform_ethernet_switch_port_vlan_EthSwitchVlanMemberMode_MIN platform_ethernet_switch_port_vlan_EthSwitchVlanMemberMode_ETH_SWITCH_MEMBER_UNMODIFIED
#define _platform_ethernet_switch_port_vlan_EthSwitchVlanMemberMode_MAX platform_ethernet_switch_port_vlan_EthSwitchVlanMemberMode_ETH_SWITCH_NOT_MEMBER
#define _platform_ethernet_switch_port_vlan_EthSwitchVlanMemberMode_ARRAYSIZE ((platform_ethernet_switch_port_vlan_EthSwitchVlanMemberMode)(platform_ethernet_switch_port_vlan_EthSwitchVlanMemberMode_ETH_SWITCH_NOT_MEMBER+1))


/* Initializer values for message structs */
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanMode_init_default {false, 0, false, _platform_ethernet_switch_port_vlan_EthSwitchVlanMemberMode_MIN}
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanNode_init_default {false, 0, {{NULL}, NULL}}
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanTable_init_default {{{NULL}, NULL}}
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanMode_init_zero {false, 0, false, _platform_ethernet_switch_port_vlan_EthSwitchVlanMemberMode_MIN}
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanNode_init_zero {false, 0, {{NULL}, NULL}}
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanTable_init_zero {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanTable_port_vlan_node_tag 1
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanMode_port_index_tag 1
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanMode_port_mode_tag 2
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanNode_vlan_id_tag 1
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanNode_port_vlan_tag 2

/* Struct field encoding specification for nanopb */
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanMode_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   port_index,        1) \
X(a, STATIC,   OPTIONAL, UENUM,    port_mode,         2)
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanMode_CALLBACK NULL
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanMode_DEFAULT NULL

#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanNode_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   vlan_id,           1) \
X(a, CALLBACK, REPEATED, MESSAGE,  port_vlan,         2)
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanNode_CALLBACK pb_default_field_callback
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanNode_DEFAULT NULL
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanNode_port_vlan_MSGTYPE platform_ethernet_switch_port_vlan_EthSwitchPortVlanMode

#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanTable_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  port_vlan_node,    1)
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanTable_CALLBACK pb_default_field_callback
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanTable_DEFAULT NULL
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanTable_port_vlan_node_MSGTYPE platform_ethernet_switch_port_vlan_EthSwitchPortVlanNode

extern const pb_msgdesc_t platform_ethernet_switch_port_vlan_EthSwitchPortVlanMode_msg;
extern const pb_msgdesc_t platform_ethernet_switch_port_vlan_EthSwitchPortVlanNode_msg;
extern const pb_msgdesc_t platform_ethernet_switch_port_vlan_EthSwitchPortVlanTable_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanMode_fields &platform_ethernet_switch_port_vlan_EthSwitchPortVlanMode_msg
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanNode_fields &platform_ethernet_switch_port_vlan_EthSwitchPortVlanNode_msg
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanTable_fields &platform_ethernet_switch_port_vlan_EthSwitchPortVlanTable_msg

/* Maximum encoded size of messages (where known) */
#define platform_ethernet_switch_port_vlan_EthSwitchPortVlanMode_size 8
/* platform_ethernet_switch_port_vlan_EthSwitchPortVlanNode_size depends on runtime parameters */
/* platform_ethernet_switch_port_vlan_EthSwitchPortVlanTable_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
