/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "platform/device/driver/ethernet_manager/proto/switch/port_vlan_cfg.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(platform_ethernet_switch_port_vlan_EthSwitchPortVlanMode, platform_ethernet_switch_port_vlan_EthSwitchPortVlanMode, AUTO)


PB_BIND(platform_ethernet_switch_port_vlan_EthSwitchPortVlanNode, platform_ethernet_switch_port_vlan_EthSwitchPortVlanNode, AUTO)


PB_BIND(platform_ethernet_switch_port_vlan_EthSwitchPortVlanTable, platform_ethernet_switch_port_vlan_EthSwitchPortVlanTable, AUTO)




