/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_PLATFORM_ETHERNET_SWITCH_PORT_PLATFORM_DEVICE_DRIVER_ETHERNET_MANAGER_PROTO_SWITCH_PORT_CFG_PB_H_INCLUDED
#define PB_PLATFORM_ETHERNET_SWITCH_PORT_PLATFORM_DEVICE_DRIVER_ETHERNET_MANAGER_PROTO_SWITCH_PORT_CFG_PB_H_INCLUDED
#include <pb.h>
#include "platform/device/driver/ethernet_manager/proto/common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _platform_ethernet_switch_port_EthSwitchVlanStrategy {
    platform_ethernet_switch_port_EthSwitchVlanStrategy_ETH_SWITCH_8021Q_DISABLE = 0,
    platform_ethernet_switch_port_EthSwitchVlanStrategy_ETH_SWITCH_8021Q_FALLBACK = 1,
    platform_ethernet_switch_port_EthSwitchVlanStrategy_ETH_SWITCH_8021Q_CHECK = 2,
    platform_ethernet_switch_port_EthSwitchVlanStrategy_ETH_SWITCH_8021Q_SECURE = 3
} platform_ethernet_switch_port_EthSwitchVlanStrategy;

/* Struct definitions */
typedef struct _platform_ethernet_switch_port_EthSwitchPortTable {
    pb_callback_t port;
} platform_ethernet_switch_port_EthSwitchPortTable;

typedef struct _platform_ethernet_switch_port_EthSwitchPort {
    bool has_port_index;
    uint32_t port_index;
    bool has_default_vlan_id;
    uint32_t default_vlan_id;
    bool has_force_default_vlan_id;
    bool force_default_vlan_id;
    bool has_allow_vlan_id_zero;
    bool allow_vlan_id_zero;
    bool has_vlan_strategy;
    platform_ethernet_switch_port_EthSwitchVlanStrategy vlan_strategy;
    bool has_speed;
    platform_ethernet_common_EthSpeedType speed;
} platform_ethernet_switch_port_EthSwitchPort;


/* Helper constants for enums */
#define _platform_ethernet_switch_port_EthSwitchVlanStrategy_MIN platform_ethernet_switch_port_EthSwitchVlanStrategy_ETH_SWITCH_8021Q_DISABLE
#define _platform_ethernet_switch_port_EthSwitchVlanStrategy_MAX platform_ethernet_switch_port_EthSwitchVlanStrategy_ETH_SWITCH_8021Q_SECURE
#define _platform_ethernet_switch_port_EthSwitchVlanStrategy_ARRAYSIZE ((platform_ethernet_switch_port_EthSwitchVlanStrategy)(platform_ethernet_switch_port_EthSwitchVlanStrategy_ETH_SWITCH_8021Q_SECURE+1))


/* Initializer values for message structs */
#define platform_ethernet_switch_port_EthSwitchPort_init_default {false, 0, false, 0, false, 0, false, 0, false, _platform_ethernet_switch_port_EthSwitchVlanStrategy_MIN, false, _platform_ethernet_common_EthSpeedType_MIN}
#define platform_ethernet_switch_port_EthSwitchPortTable_init_default {{{NULL}, NULL}}
#define platform_ethernet_switch_port_EthSwitchPort_init_zero {false, 0, false, 0, false, 0, false, 0, false, _platform_ethernet_switch_port_EthSwitchVlanStrategy_MIN, false, _platform_ethernet_common_EthSpeedType_MIN}
#define platform_ethernet_switch_port_EthSwitchPortTable_init_zero {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define platform_ethernet_switch_port_EthSwitchPortTable_port_tag 1
#define platform_ethernet_switch_port_EthSwitchPort_port_index_tag 1
#define platform_ethernet_switch_port_EthSwitchPort_default_vlan_id_tag 2
#define platform_ethernet_switch_port_EthSwitchPort_force_default_vlan_id_tag 3
#define platform_ethernet_switch_port_EthSwitchPort_allow_vlan_id_zero_tag 4
#define platform_ethernet_switch_port_EthSwitchPort_vlan_strategy_tag 5
#define platform_ethernet_switch_port_EthSwitchPort_speed_tag 6

/* Struct field encoding specification for nanopb */
#define platform_ethernet_switch_port_EthSwitchPort_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   port_index,        1) \
X(a, STATIC,   OPTIONAL, UINT32,   default_vlan_id,   2) \
X(a, STATIC,   OPTIONAL, BOOL,     force_default_vlan_id,   3) \
X(a, STATIC,   OPTIONAL, BOOL,     allow_vlan_id_zero,   4) \
X(a, STATIC,   OPTIONAL, UENUM,    vlan_strategy,     5) \
X(a, STATIC,   OPTIONAL, UENUM,    speed,             6)
#define platform_ethernet_switch_port_EthSwitchPort_CALLBACK NULL
#define platform_ethernet_switch_port_EthSwitchPort_DEFAULT NULL

#define platform_ethernet_switch_port_EthSwitchPortTable_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  port,              1)
#define platform_ethernet_switch_port_EthSwitchPortTable_CALLBACK pb_default_field_callback
#define platform_ethernet_switch_port_EthSwitchPortTable_DEFAULT NULL
#define platform_ethernet_switch_port_EthSwitchPortTable_port_MSGTYPE platform_ethernet_switch_port_EthSwitchPort

extern const pb_msgdesc_t platform_ethernet_switch_port_EthSwitchPort_msg;
extern const pb_msgdesc_t platform_ethernet_switch_port_EthSwitchPortTable_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define platform_ethernet_switch_port_EthSwitchPort_fields &platform_ethernet_switch_port_EthSwitchPort_msg
#define platform_ethernet_switch_port_EthSwitchPortTable_fields &platform_ethernet_switch_port_EthSwitchPortTable_msg

/* Maximum encoded size of messages (where known) */
#define platform_ethernet_switch_port_EthSwitchPort_size 20
/* platform_ethernet_switch_port_EthSwitchPortTable_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
